name: cloudflare

on:
  workflow_dispatch:

jobs:
  cloudflare:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Wrangler (latest version)
        run: npm install -g wrangler@3.90.0

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: deploy
          secrets: |
            GTKK
        env:
          GTKK: ${{ secrets.GTKK }}