name: FCE

on:
  workflow_dispatch:
    inputs:
      firmware_url:
        description: 'enter the firmware.zip URL'
        required: true
        type: string
      extract_type:
        description: 'Select what to extract'
        required: true
        type: choice
        options:
          - settings_apk
          - boot_img
          - both

jobs:
  fce:
    runs-on: ubuntu-latest

    env:
      BOOT_IMG: false
      SETTINGS_APK: false
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      FIRMWARE_URL: ${{ github.event.inputs.firmware_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set environment
        run: |
          FIRMWARE_NAME=$(basename "${{ github.event.inputs.firmware_url }}" .zip)
          echo "FIRMWARE_NAME=$FIRMWARE_NAME" >> $GITHUB_ENV

          if [ "${{ github.event.inputs.extract_type }}" == "both" ]; then
            echo "BOOT_IMG=true" >> $GITHUB_ENV
            echo "SETTINGS_APK=true" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.extract_type }}" == "boot_img" ]; then
            echo "BOOT_IMG=true" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.extract_type }}" == "settings_apk" ]; then
            echo "SETTINGS_APK=true" >> $GITHUB_ENV
          fi

      - name: Cache pip and tools dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.local/lib/python3*/site-packages
            tools
          key: ${{ runner.os }}-cache-${{ hashFiles('**/tools/*') }}
          restore-keys: |
            ${{ runner.os }}-cache-

      - name: Install dependencies
        run: |
          if [ ! -d tools ]; then
            sudo apt-get update && sudo apt-get install -y python3-pip p7zip-full aria2
            git clone https://github.com/vm03/payload_dumper.git tools
            aria2c -o erofs-utils.zip https://github.com/sekaiacg/erofs-utils/releases/download/v1.8.1-240810/erofs-utils-v1.8.1-gddbed144-Linux_x86_64-2408101422.zip
            7z x erofs-utils.zip -otools
            pip install -r ./tools/requirements.txt
            rm -f erofs-utils.zip
          fi
          
      - name: Extract firmware name from URL
        run: |
          aria2c -x 7 -s 7 -k 1M --continue --max-tries=0 --log=LOG --out='exrom.zip' "$FIRMWARE_URL"
          7z x exrom.zip -o./
          rm exrom.zip

          if [ "$BOOT_IMG" == "true" ]; then
            if [ ! -f "boot.img" ]; then
              ./tools/payload_dumper.py --out . --images boot payload.bin
            fi
            7z a "Boot_img_${FIRMWARE_NAME}.zip" boot.img
            rm boot.img
            if ! git ls-remote --tags origin | grep -q "Boot_img"; then
              git tag "Boot_img"
              git push origin "Boot_img"
            fi
            if ! gh release view "Boot_img"; then
              gh release create Boot_img --title "Boot_img" --notes "Boot_img"
            fi          
            gh release upload Boot_img "Boot_img_${FIRMWARE_NAME}.zip" --clobber
          fi

          if [ "$SETTINGS_APK" == "true" ]; then
            ./tools/payload_dumper.py --out . --images system_ext payload.bin
            sudo mkdir -p /mnt/priv-app/Settings && sudo chmod -R 777 /mnt && 7z x system_ext.img -o/mnt -y && sudo cp /mnt/priv-app/Settings/Settings.apk . && echo "method 1 used" || (./tools/extract.erofs -i system_ext.img -x -o . && cp system_ext/priv-app/Settings/Settings.apk . && echo "method 2 used" || (echo "both methods failed" && exit 1))
            7z a "Settings_apk_${FIRMWARE_NAME}.zip" Settings.apk
            rm Settings.apk
            if ! git ls-remote --tags origin | grep -q "settings_apk"; then
              git tag "settings_apk"
              git push origin "settings_apk"
            fi
            if ! gh release view "settings_apk"; then
              gh release create settings_apk --title "settings_apk" --notes "settings_apk"
            fi          
            gh release upload settings_apk "Settings_apk_${FIRMWARE_NAME}.zip" --clobber
          fi