name: Deploy Workflow

on:
  workflow_dispatch:
    inputs:
      deploy_version:
        description: 'Version to deploy'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    name: ${{ github.event.inputs.deploy_version }} 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy application
        run: |
          echo "Deploying version ${{ github.event.inputs.deploy_version }}"